version: '3.8'  # Add this line at the top
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: poll_db
      POSTGRES_USER: poll_user
      POSTGRES_PASSWORD: poll_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poll_user -d poll_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  http:
    build:
      context: ./http
      dockerfile: Dockerfile
    container_name: http_api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./http/.env
    ports:
      - "3000:3000"
    volumes:
      - ./http:/app
      - /app/node_modules
    command: ["pnpm", "dev"]  
  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: websocket_server
    depends_on:
      - http
    env_file:
      - ./websocket/.env
    ports:
      - "8080:8080"
    volumes:
      - ./websocket:/app
      - /app/node_modules
    command: ["pnpm", "dev"] 

volumes:
  postgres_data: